Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "agent-vm"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  # Reseau prive pour joindre la VM Jenkins
  config.vm.network "private_network", ip: "192.168.56.11"
end
